"use client";

import Image from "next/image";
import { useState, type FormEvent } from "react";
import { ArrowRight, Bot, CheckCircle2, Mail, MapPin, MessageSquareText, Phone, TrendingUp, Users2 } from "lucide-react";

type ContactForm = { name: string; email: string; company: string; message: string };

export function MarketingContactPage() {
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const [form, setForm] = useState<ContactForm>({ name: "", email: "", company: "", message: "" });

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSending(true);
    await new Promise((resolve) => window.setTimeout(resolve, 800));
    setSending(false);
    setSent(true);
  }

  return (
    <>
      <section className="relative overflow-hidden border-b border-[#e2e8e3]"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-[#fffdf9] via-[#faf7f2] to-[#f0ede7]" /><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="mx-auto max-w-xl text-center animate-fade-in"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#f9ae5a]/30 bg-[#f9ae5a]/10 px-3.5 py-1.5 text-[11px] font-bold uppercase tracking-widest text-[#b66d1e]"><MessageSquareText className="h-3 w-3" />Demo aanvragen</div><h1 className="text-[2.6rem] font-extrabold leading-tight text-[#0d1520] sm:text-5xl">Bekijk hoe Lead Finder in jouw <span className="gradient-text">proces past.</span></h1><p className="mt-5 text-base leading-7 text-[#4d5b6b]">Plan een demo, bespreek je huidige leadflow en ontdek welke bundels meteen waarde kunnen leveren.</p></div></div></section>
      <section className="bg-[#f7f8f6] py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-7 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-[#e2e8e3] bg-white p-7 shadow-sm sm:p-9">{sent ? <div className="flex flex-col items-center justify-center py-14 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#12a66a]/15"><CheckCircle2 className="h-8 w-8 text-[#12a66a]" /></div><h2 className="mt-6 text-2xl font-extrabold text-[#0d1520]">Bericht verzonden!</h2><p className="mt-2 text-sm text-[#5a6878]">We nemen zo snel mogelijk contact met je op — meestal binnen 1 werkdag.</p><button onClick={() => setSent(false)} className="mt-5 text-sm font-semibold text-[#f9ae5a]">Nieuw bericht sturen</button></div> : <><h2 className="text-xl font-extrabold text-[#0d1520]">Stuur ons een bericht</h2><p className="mt-1 text-sm text-[#5a6878]">We reageren doorgaans binnen 1 werkdag.</p><form onSubmit={handleSubmit} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2">{([{ id: "name", label: "Naam *", type: "text", placeholder: "Jouw naam", required: true }, { id: "email", label: "E-mail *", type: "email", placeholder: "jij@bedrijf.be", required: true }] as const).map((field) => <label key={field.id} className="block text-sm font-bold text-[#344052]">{field.label}<input type={field.type} required={field.required} value={form[field.id]} onChange={(event) => setForm({ ...form, [field.id]: event.target.value })} placeholder={field.placeholder} className="mt-1.5 w-full rounded-xl border border-[#dde3e8] bg-[#f9fbfa] px-3.5 py-2.5 font-normal outline-none focus:border-[#f9ae5a] focus:bg-white focus:ring-2 focus:ring-[#f9ae5a]/20" /></label>)}</div><label className="block text-sm font-bold text-[#344052]">Bedrijf<input type="text" value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} placeholder="Bedrijfsnaam" className="mt-1.5 w-full rounded-xl border border-[#dde3e8] bg-[#f9fbfa] px-3.5 py-2.5 font-normal outline-none focus:border-[#f9ae5a] focus:bg-white focus:ring-2 focus:ring-[#f9ae5a]/20" /></label><label className="block text-sm font-bold text-[#344052]">Bericht *<textarea required rows={4} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} placeholder="Vertel over je huidige leadflow..." className="mt-1.5 w-full resize-none rounded-xl border border-[#dde3e8] bg-[#f9fbfa] px-3.5 py-2.5 font-normal outline-none focus:border-[#f9ae5a] focus:bg-white focus:ring-2 focus:ring-[#f9ae5a]/20" /></label><button type="submit" disabled={sending} className="inline-flex h-11 w-full items-center justify-center rounded-xl bg-[#f9ae5a] text-sm font-bold text-[#14100b] disabled:opacity-60">{sending ? "Verzenden..." : <><span>Stuur bericht</span><ArrowRight className="ml-2 h-4 w-4" /></>}</button></form></>}</div>
      <div className="space-y-4"><div className="rounded-2xl border border-[#f9ae5a]/20 bg-[#fffbf5] p-5"><div className="mb-4 flex items-center gap-2"><Image src="/favicon.ico" alt="Digitify" width={28} height={28} className="rounded-lg" /><p className="text-[11px] font-bold uppercase tracking-wider text-[#b66d1e]">Wat je krijgt in de demo</p></div><ul className="space-y-3">{[{ icon: Users2, text: "Analyse van je huidige prospectieproces." }, { icon: MessageSquareText, text: "Walkthrough van leads, campagnes, offertes en bookings." }, { icon: Bot, text: "Advies over welke bundels je best eerst activeert." }, { icon: TrendingUp, text: "Schatting van de tijdsbesparing voor jouw team." }].map(({ icon: Icon, text }) => <li key={text} className="flex gap-2.5 text-sm text-[#4d5b6b]"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-[#12a66a]" />{text}</li>)}</ul></div><div className="rounded-2xl border border-[#e2e8e3] bg-white p-5 shadow-sm"><p className="mb-3 text-sm font-bold text-[#0d1520]">Contactgegevens</p>{[{ icon: Mail, text: "hello@digitify.be", href: "mailto:hello@digitify.be" }, { icon: Phone, text: "+32 (0) 486 51 57 73", href: "tel:+3248651573" }, { icon: MapPin, text: "België" }].map(({ icon: Icon, text, href }) => <div key={text} className="flex items-center gap-3 py-2 text-sm text-[#4d5b6b]"><Icon className="h-4 w-4 text-[#f9ae5a]" />{href ? <a href={href}>{text}</a> : text}</div>)}</div></div></div></div></section>
    </>
  );
}
