import { MODEL_COST_USD } from "./model-costs";

export type MediaModelType =
  | "IMAGE"
  | "IMAGE_I2I"
  | "VIDEO"
  | "VIDEO_I2V"
  | "MARKETING_AD"
  | "LIP_SYNC";

export type MediaModelDefinition = {
  id: string;
  label: string;
  type: MediaModelType;
  endpoint: string;
  description?: string;
  costUsd?: number;
  aspectRatios?: string[];
  resolutions?: string[];
  durations?: number[];
  qualities?: string[];
  defaultAspectRatio?: string;
  imageField?: string;
  maxReferenceImages?: number;
  lipSyncMode?: "PORTRAIT" | "VIDEO";
};

function withModelCost(model: MediaModelDefinition): MediaModelDefinition {
  const costUsd = MODEL_COST_USD[model.endpoint];
  return costUsd == null ? model : { ...model, costUsd };
}

const IMAGE_ASPECT = ["1:1", "4:5", "9:16", "16:9", "3:4"] as const;
const VIDEO_ASPECT = ["9:16", "16:9", "1:1", "4:3", "3:4"] as const;
const VIDEO_DURATIONS = [5, 10] as const;
const VIDEO_DURATIONS_LONG = [5, 10, 15] as const;
const MARKETING_DURATIONS = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] as const;

export const IMAGE_MODELS: MediaModelDefinition[] = [
  {
    id: "flux-schnell",
    label: "Flux Schnell",
    type: "IMAGE",
    endpoint: "flux-schnell",
    description: "Zeer snelle Flux-variant voor snelle iteratie",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-dev",
    label: "Flux Dev",
    type: "IMAGE",
    endpoint: "flux-dev",
    description: "Snelle, hoogwaardige tekst-naar-afbeelding",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-2-dev",
    label: "Flux 2 Dev",
    type: "IMAGE",
    endpoint: "flux-2-dev",
    description: "Flux 2 — sterke prompt-trouw en detail",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-kontext-dev-t2i",
    label: "Flux Kontext Dev",
    type: "IMAGE",
    endpoint: "flux-kontext-dev-t2i",
    description: "Tekst-naar-afbeelding met optionele stijlreferentie",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-kontext-pro-t2i",
    label: "Flux Kontext Pro",
    type: "IMAGE",
    endpoint: "flux-kontext-pro-t2i",
    description: "Hogere kwaliteit Kontext voor campagnebeelden",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "hidream-i1-fast",
    label: "HiDream Fast",
    type: "IMAGE",
    endpoint: "hidream-i1-fast",
    description: "Snel HiDream-model voor concepten",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "hidream-i1-dev",
    label: "HiDream Dev",
    type: "IMAGE",
    endpoint: "hidream-i1-dev",
    description: "Balans tussen snelheid en kwaliteit",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "hidream-i1-full",
    label: "HiDream Full",
    type: "IMAGE",
    endpoint: "hidream-i1-full",
    description: "Maximale HiDream-kwaliteit",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "nano-banana",
    label: "Nano Banana",
    type: "IMAGE",
    endpoint: "nano-banana",
    description: "Gemini Flash Image — compact en snel",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    defaultAspectRatio: "1:1",
  },
  {
    id: "nano-banana-2",
    label: "Nano Banana 2",
    type: "IMAGE",
    endpoint: "nano-banana-2",
    description: "Google Gemini Flash Image — scherp en veelzijdig",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    resolutions: ["1K", "2K", "4K"],
    defaultAspectRatio: "1:1",
  },
  {
    id: "nano-banana-pro",
    label: "Nano Banana Pro",
    type: "IMAGE",
    endpoint: "nano-banana-pro",
    description: "Premium Gemini-image met hogere detaildichtheid",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    resolutions: ["1K", "2K", "4K"],
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v3",
    label: "Seedream v3",
    type: "IMAGE",
    endpoint: "bytedance-seedream-v3",
    description: "Artistieke Seedream met levendige kleuren",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v4",
    label: "Seedream v4",
    type: "IMAGE",
    endpoint: "bytedance-seedream-v4",
    description: "Hoge betrouwbaarheid voor realistische campagnebeelden",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v4.5",
    label: "Seedream v4.5",
    type: "IMAGE",
    endpoint: "bytedance-seedream-v4.5",
    description: "Cinematisch Seedream met sterk contrast",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "seedream-5.0",
    label: "Seedream 5.0",
    type: "IMAGE",
    endpoint: "bytedance-seedream-v5.0",
    description: "ByteDance model met hoge detailkwaliteit",
    aspectRatios: [...IMAGE_ASPECT],
    qualities: ["basic", "high"],
    defaultAspectRatio: "1:1",
  },
  {
    id: "gpt-image-1.5",
    label: "GPT Image 1.5",
    type: "IMAGE",
    endpoint: "gpt-image-1.5",
    description: "OpenAI image — sterk in tekst en layouts",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "gpt4o-text-to-image",
    label: "GPT-4o Image",
    type: "IMAGE",
    endpoint: "gpt4o-text-to-image",
    description: "GPT-4o tekst-naar-afbeelding",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "midjourney-v7",
    label: "Midjourney v7",
    type: "IMAGE",
    endpoint: "midjourney-v7",
    description: "Midjourney-stijl via API",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "midjourney-v8",
    label: "Midjourney v8",
    type: "IMAGE",
    endpoint: "midjourney-v8",
    description: "Nieuwste Midjourney-variant",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "qwen-image",
    label: "Qwen Image",
    type: "IMAGE",
    endpoint: "qwen-image",
    description: "Qwen tekst-naar-afbeelding",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "reve-text-to-image",
    label: "Reve",
    type: "IMAGE",
    endpoint: "reve-text-to-image",
    description: "Reve — sterk in product- en lifestylebeelden",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "google-imagen4-fast",
    label: "Imagen 4 Fast",
    type: "IMAGE",
    endpoint: "google-imagen4-fast",
    description: "Google Imagen 4 — snel en toegankelijk",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
  {
    id: "ideogram-v3-t2i",
    label: "Ideogram v3",
    type: "IMAGE",
    endpoint: "ideogram-v3-t2i",
    description: "Ideogram — uitstekend voor tekst in beeld",
    aspectRatios: [...IMAGE_ASPECT],
    defaultAspectRatio: "1:1",
  },
];

export const IMAGE_I2I_MODELS: MediaModelDefinition[] = [
  {
    id: "nano-banana-edit",
    label: "Nano Banana Edit",
    type: "IMAGE_I2I",
    endpoint: "nano-banana-edit",
    description: "Bewerk afbeeldingen met Gemini",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "nano-banana-2-edit",
    label: "Nano Banana 2 Edit",
    type: "IMAGE_I2I",
    endpoint: "nano-banana-2-edit",
    description: "Bewerk of varieer een referentie-afbeelding",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "nano-banana-pro-edit",
    label: "Nano Banana Pro Edit",
    type: "IMAGE_I2I",
    endpoint: "nano-banana-pro-edit",
    description: "Premium bewerking met meerdere referenties",
    aspectRatios: ["1:1", "4:5", "9:16", "16:9"],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-kontext-dev",
    label: "Flux Kontext Dev Edit",
    type: "IMAGE_I2I",
    endpoint: "flux-kontext-dev-i2i",
    description: "Contextbewuste image-to-image transformatie",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "image_url",
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-kontext-pro-i2i",
    label: "Flux Kontext Pro Edit",
    type: "IMAGE_I2I",
    endpoint: "flux-kontext-pro-i2i",
    description: "Pro Kontext voor nauwkeurige bewerkingen",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "image_url",
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-kontext-max-i2i",
    label: "Flux Kontext Max Edit",
    type: "IMAGE_I2I",
    endpoint: "flux-kontext-max-i2i",
    description: "Maximale Kontext-kwaliteit voor retouche",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "image_url",
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v4-edit",
    label: "Seedream v4 Edit",
    type: "IMAGE_I2I",
    endpoint: "bytedance-seedream-v4-edit",
    description: "Varieer Seedream v4 vanaf referentie",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v4.5-edit",
    label: "Seedream v4.5 Edit",
    type: "IMAGE_I2I",
    endpoint: "bytedance-seedream-v4.5-edit",
    description: "Seedream v4.5 image-to-image",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seedream-v5.0-edit",
    label: "Seedream 5.0 Edit",
    type: "IMAGE_I2I",
    endpoint: "bytedance-seedream-v5.0-edit",
    description: "Seedream 5.0 bewerking en variaties",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "bytedance-seededit-v3",
    label: "SeedEdit v3",
    type: "IMAGE_I2I",
    endpoint: "bytedance-seededit-v3",
    description: "ByteDance SeedEdit voor gerichte aanpassingen",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "gpt4o-edit",
    label: "GPT-4o Edit",
    type: "IMAGE_I2I",
    endpoint: "gpt4o-edit",
    description: "Bewerk beelden met GPT-4o",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "gpt-image-1.5-edit",
    label: "GPT Image 1.5 Edit",
    type: "IMAGE_I2I",
    endpoint: "gpt-image-1.5-edit",
    description: "OpenAI image editing",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "qwen-image-edit",
    label: "Qwen Image Edit",
    type: "IMAGE_I2I",
    endpoint: "qwen-image-edit",
    description: "Qwen bewerking van referentiebeelden",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "reve-image-edit",
    label: "Reve Edit",
    type: "IMAGE_I2I",
    endpoint: "reve-image-edit",
    description: "Reve image-to-image voor productshots",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-2-flex-edit",
    label: "Flux 2 Flex Edit",
    type: "IMAGE_I2I",
    endpoint: "flux-2-flex-edit",
    description: "Flux 2 Flex bewerking met meerdere referenties",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    maxReferenceImages: 8,
    defaultAspectRatio: "1:1",
  },
  {
    id: "flux-2-pro-edit",
    label: "Flux 2 Pro Edit",
    type: "IMAGE_I2I",
    endpoint: "flux-2-pro-edit",
    description: "Flux 2 Pro image-to-image",
    aspectRatios: [...IMAGE_ASPECT],
    imageField: "images_list",
    maxReferenceImages: 8,
    defaultAspectRatio: "1:1",
  },
];

export const VIDEO_MODELS: MediaModelDefinition[] = [
  {
    id: "seedance-pro-t2v-fast",
    label: "Seedance Pro Fast",
    type: "VIDEO",
    endpoint: "seedance-pro-t2v-fast",
    description: "Snelle Seedance tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "seedance-lite-t2v",
    label: "Seedance Lite",
    type: "VIDEO",
    endpoint: "seedance-lite-t2v",
    description: "Lichtgewicht Seedance voor social clips",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "seedance-2.0",
    label: "Seedance Pro",
    type: "VIDEO",
    endpoint: "seedance-pro-t2v",
    description: "ByteDance video met sterke beweging",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.5-turbo-pro-t2v",
    label: "Kling 2.5 Turbo Pro",
    type: "VIDEO",
    endpoint: "kling-v2.5-turbo-pro-t2v",
    description: "Snelle Kling Pro voor reels en ads",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.1",
    label: "Kling v2.1 Master",
    type: "VIDEO",
    endpoint: "kling-v2.1-master-t2v",
    description: "Cinematische Kling Master tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.6-pro-t2v",
    label: "Kling 2.6 Pro",
    type: "VIDEO",
    endpoint: "kling-v2.6-pro-t2v",
    description: "Nieuwste Kling Pro met hoge motion-kwaliteit",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "veo3-fast-text-to-video",
    label: "Veo 3 Fast",
    type: "VIDEO",
    endpoint: "veo3-fast-text-to-video",
    description: "Google Veo 3 — snelle fotorealistische video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "16:9",
  },
  {
    id: "veo3.1-lite-text-to-video",
    label: "Veo 3.1 Lite",
    type: "VIDEO",
    endpoint: "veo3.1-lite-text-to-video",
    description: "Lichte Veo-variant voor snelle concepten",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "16:9",
  },
  {
    id: "wan2.7-text-to-video",
    label: "Wan 2.7",
    type: "VIDEO",
    endpoint: "wan2.7-text-to-video",
    description: "Wan tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "pixverse-v5.5-t2v",
    label: "PixVerse v5.5",
    type: "VIDEO",
    endpoint: "pixverse-v5.5-t2v",
    description: "PixVerse social video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "minimax-hailuo-02-standard-t2v",
    label: "Hailuo 02 Standard",
    type: "VIDEO",
    endpoint: "minimax-hailuo-02-standard-t2v",
    description: "MiniMax Hailuo standaard tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "runway-text-to-video",
    label: "Runway Gen",
    type: "VIDEO",
    endpoint: "runway-text-to-video",
    description: "Runway tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "16:9",
  },
  {
    id: "hunyuan-fast-text-to-video",
    label: "Hunyuan Fast",
    type: "VIDEO",
    endpoint: "hunyuan-fast-text-to-video",
    description: "Tencent Hunyuan — snelle video-generatie",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    defaultAspectRatio: "9:16",
  },
  {
    id: "sd-2-t2v",
    label: "Seedance 2.0",
    type: "VIDEO",
    endpoint: "sd-2-t2v",
    description: "ByteDance Seedance 2.0 tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    qualities: ["basic", "high"],
    defaultAspectRatio: "9:16",
  },
  {
    id: "grok-imagine-t2v",
    label: "Grok Imagine T2V",
    type: "VIDEO",
    endpoint: "grok-imagine-t2v",
    description: "xAI Grok — cinematische tekst-naar-video",
    aspectRatios: ["9:16", "16:9", "2:3", "3:2", "1:1"],
    durations: [6, 10, 15],
    qualities: ["fun", "normal", "spicy"],
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v3-t2v",
    label: "Kling v3",
    type: "VIDEO",
    endpoint: "kling-v3-t2v",
    description: "Nieuwste Kling v3 tekst-naar-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    defaultAspectRatio: "9:16",
  },
];

export const VIDEO_I2V_MODELS: MediaModelDefinition[] = [
  {
    id: "seedance-pro-i2v-fast",
    label: "Seedance Pro I2V Fast",
    type: "VIDEO_I2V",
    endpoint: "seedance-pro-i2v-fast",
    description: "Snelle Seedance image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "seedance-pro-i2v",
    label: "Seedance Pro I2V",
    type: "VIDEO_I2V",
    endpoint: "seedance-pro-i2v",
    description: "Seedance vanaf startframe",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.1-i2v",
    label: "Kling v2.1 Standard I2V",
    type: "VIDEO_I2V",
    endpoint: "kling-v2.1-standard-i2v",
    description: "Animeer een startframe naar video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.1-pro-i2v",
    label: "Kling v2.1 Pro I2V",
    type: "VIDEO_I2V",
    endpoint: "kling-v2.1-pro-i2v",
    description: "Kling Pro image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "kling-v2.5-turbo-pro-i2v",
    label: "Kling 2.5 Turbo Pro I2V",
    type: "VIDEO_I2V",
    endpoint: "kling-v2.5-turbo-pro-i2v",
    description: "Snelle Kling Pro vanaf startframe",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "veo3-fast-image-to-video",
    label: "Veo 3 Fast I2V",
    type: "VIDEO_I2V",
    endpoint: "veo3-fast-image-to-video",
    description: "Google Veo 3 vanaf afbeelding",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "16:9",
  },
  {
    id: "sd-2-i2v",
    label: "Seedance 2 I2V",
    type: "VIDEO_I2V",
    endpoint: "sd-2-i2v",
    description: "Seedance 2 image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "sd-2-image-to-video-fast",
    label: "Seedance 2 I2V Fast",
    type: "VIDEO_I2V",
    endpoint: "sd-2-image-to-video-fast",
    description: "Snelle Seedance 2 image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "pixverse-v5.5-i2v",
    label: "PixVerse v5.5 I2V",
    type: "VIDEO_I2V",
    endpoint: "pixverse-v5.5-i2v",
    description: "PixVerse image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "minimax-hailuo-02-standard-i2v",
    label: "Hailuo 02 Standard I2V",
    type: "VIDEO_I2V",
    endpoint: "minimax-hailuo-02-standard-i2v",
    description: "Hailuo vanaf startframe",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "runway-image-to-video",
    label: "Runway I2V",
    type: "VIDEO_I2V",
    endpoint: "runway-image-to-video",
    description: "Runway image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "16:9",
  },
  {
    id: "wan2.7-image-to-video",
    label: "Wan 2.7 I2V",
    type: "VIDEO_I2V",
    endpoint: "wan2.7-image-to-video",
    description: "Wan image-to-video",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
  {
    id: "sd-2-i2v-multi",
    label: "Seedance 2.0 I2V",
    type: "VIDEO_I2V",
    endpoint: "sd-2-i2v",
    description: "Seedance 2.0 vanaf startframe — tot 9 referenties",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...VIDEO_DURATIONS_LONG],
    qualities: ["basic", "high"],
    imageField: "images_list",
    maxReferenceImages: 9,
    defaultAspectRatio: "9:16",
  },
  {
    id: "grok-imagine-i2v",
    label: "Grok Imagine I2V",
    type: "VIDEO_I2V",
    endpoint: "grok-imagine-i2v",
    description: "xAI Grok — animeer een still naar video",
    aspectRatios: ["9:16", "16:9", "2:3", "3:2", "1:1"],
    durations: [6, 10, 15],
    qualities: ["fun", "normal", "spicy"],
    imageField: "image_url",
    defaultAspectRatio: "9:16",
  },
];

export const MARKETING_AD_MODELS: MediaModelDefinition[] = [
  {
    id: "sd-2-vip-omni-reference-fast",
    label: "Marketing Ad Fast (720p)",
    type: "MARKETING_AD",
    endpoint: "sd-2-vip-omni-reference-fast",
    description: "Snellere product + avatar + script naar video-ad",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...MARKETING_DURATIONS],
    resolutions: ["720p"],
    defaultAspectRatio: "9:16",
  },
  {
    id: "seedance-2-vip-omni-reference",
    label: "Marketing Ad (720p)",
    type: "MARKETING_AD",
    endpoint: "sd-2-vip-omni-reference",
    description: "Product + avatar + script naar video-ad",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...MARKETING_DURATIONS],
    resolutions: ["720p", "1080p"],
    defaultAspectRatio: "9:16",
  },
  {
    id: "sd-2-omni-reference",
    label: "Marketing Ad Omni",
    type: "MARKETING_AD",
    endpoint: "sd-2-omni-reference",
    description: "Omni-reference ad zonder VIP-tier",
    aspectRatios: [...VIDEO_ASPECT],
    durations: [...MARKETING_DURATIONS],
    resolutions: ["720p"],
    defaultAspectRatio: "9:16",
  },
];

export const LIP_SYNC_MODELS: MediaModelDefinition[] = [
  {
    id: "infinitetalk-image-to-video",
    label: "Infinite Talk",
    type: "LIP_SYNC",
    endpoint: "infinitetalk-image-to-video",
    description: "Portret + audio → pratende video",
    resolutions: ["480p", "720p"],
    lipSyncMode: "PORTRAIT",
    defaultAspectRatio: "9:16",
  },
  {
    id: "wan2.2-speech-to-video",
    label: "Wan 2.2 Speech to Video",
    type: "LIP_SYNC",
    endpoint: "wan2.2-speech-to-video",
    description: "Wan speech-driven talking video",
    resolutions: ["480p", "720p"],
    lipSyncMode: "PORTRAIT",
    defaultAspectRatio: "9:16",
  },
  {
    id: "ltx-2.3-lipsync",
    label: "LTX 2.3 Lipsync",
    type: "LIP_SYNC",
    endpoint: "ltx-2.3-lipsync",
    description: "LTX lipsync met hoge lip-sync nauwkeurigheid",
    resolutions: ["480p", "720p", "1080p"],
    lipSyncMode: "PORTRAIT",
    defaultAspectRatio: "9:16",
  },
  {
    id: "ltx-2-19b-lipsync",
    label: "LTX 2 19B Lipsync",
    type: "LIP_SYNC",
    endpoint: "ltx-2-19b-lipsync",
    description: "LTX 19B lipsync model",
    resolutions: ["480p", "720p", "1080p"],
    lipSyncMode: "PORTRAIT",
    defaultAspectRatio: "9:16",
  },
  {
    id: "sync-lipsync",
    label: "Sync Lipsync",
    type: "LIP_SYNC",
    endpoint: "sync-lipsync",
    description: "Video + audio lipsync",
    lipSyncMode: "VIDEO",
    defaultAspectRatio: "9:16",
  },
  {
    id: "latentsync-video",
    label: "LatentSync",
    type: "LIP_SYNC",
    endpoint: "latentsync-video",
    description: "LatentSync video lipsync",
    lipSyncMode: "VIDEO",
    defaultAspectRatio: "9:16",
  },
  {
    id: "creatify-lipsync",
    label: "Creatify Lipsync",
    type: "LIP_SYNC",
    endpoint: "creatify-lipsync",
    description: "Creatify video lipsync",
    lipSyncMode: "VIDEO",
    defaultAspectRatio: "9:16",
  },
  {
    id: "veed-lipsync",
    label: "Veed Lipsync",
    type: "LIP_SYNC",
    endpoint: "veed-lipsync",
    description: "Veed video lipsync",
    lipSyncMode: "VIDEO",
    defaultAspectRatio: "9:16",
  },
  {
    id: "infinitetalk-video-to-video",
    label: "Infinite Talk V2V",
    type: "LIP_SYNC",
    endpoint: "infinitetalk-video-to-video",
    description: "Video + audio → lipsync video",
    resolutions: ["480p", "720p"],
    lipSyncMode: "VIDEO",
    defaultAspectRatio: "9:16",
  },
];

const ALL_MODELS = [
  ...IMAGE_MODELS,
  ...IMAGE_I2I_MODELS,
  ...VIDEO_MODELS,
  ...VIDEO_I2V_MODELS,
  ...MARKETING_AD_MODELS,
  ...LIP_SYNC_MODELS,
];

export function getModelById(id: string): MediaModelDefinition | undefined {
  const model = ALL_MODELS.find((item) => item.id === id);
  return model ? withModelCost(model) : undefined;
}

export function listModelsByType(type: MediaModelType): MediaModelDefinition[] {
  return ALL_MODELS.filter((model) => model.type === type).map(withModelCost);
}

export function listAllModels(): MediaModelDefinition[] {
  return ALL_MODELS.map(withModelCost);
}
