import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { generate } from "otplib";
import { PrismaClient, setWorkspaceRlsContext } from "@digitify/db";
import { beginLogin, finishLogin, beginFactorSetup, verifyFactorSetup, confirmFactorSetup, factorStatus, manageFactor, personalAuth, issueRecoveryGrant, beginControlledRecovery, authRateLimit } from "../lib/two-factor";
import { decryptFactor, tokenHash, upgradedPassword } from "../lib/two-factor-crypto";
import { resolveSessionIdentity } from "../lib/session-identity";

const enabled = process.env.RUN_DB_INTEGRATION === "1" && Boolean(process.env.DATABASE_URL);
describe.skipIf(!enabled)("personal 2FA PostgreSQL / concurrency", () => {
  const db = new PrismaClient(), ids: string[] = [], bucketKeys: string[] = [];
  const password = "Disposable-2FA-test-only!2026";
  beforeAll(async () => {
    process.env.TWO_FACTOR_ENCRYPTION_KEY ||= "a1".repeat(32);
    const roles = await db.$queryRaw<Array<{ rolsuper: boolean; rolbypassrls: boolean }>>`SELECT rolsuper, rolbypassrls FROM pg_roles WHERE rolname = current_user`;
    expect(roles[0]?.rolsuper || roles[0]?.rolbypassrls).toBe(false);
  });
  afterAll(async () => {
    await db.securityAuditEvent.deleteMany({ where: { targetUserId: { in: ids } } });
    // Dispose only the accounts generated by this test file; never real accounts.
    await db.user.deleteMany({ where: { id: { in: ids } } });
    await db.authRateBucket.deleteMany({ where: { key: { in: bucketKeys } } });
    await db.$disconnect();
  });
  async function account(role: "OWNER" | "VIEWER" = "OWNER", ownerId?: string) {
    const user = await db.user.create({ data: { email: `two-factor-${crypto.randomUUID()}@example.test`, role, passwordHash: upgradedPassword(password), emailVerified: new Date(), workspaceOwnerId: ownerId } });
    ids.push(user.id); return user;
  }
  async function code(secret: string) { return generate({ secret, epoch: Math.floor(Date.now() / 1000), algorithm: "sha1", digits: 6, period: 30 }); }
  async function enroll(user: { id: string }) {
    const setup = await beginFactorSetup(db, user.id, password);
    const result = await verifyFactorSetup(db, user.id, await code(setup.secret));
    await confirmFactorSetup(db, user.id, result.proof); return { ...result, secret: setup.secret };
  }
  it("completes non-2FA login only once and rejects missing, expired or revoked challenges", async () => {
    const user = await account();
    await expect(beginLogin(db, user.email, "wrong")).rejects.toThrow();
    const login = await beginLogin(db, user.email, password); expect(login.requiresTwoFactor).toBe(false);
    const race = await Promise.allSettled([finishLogin(db, login.token), finishLogin(db, login.token)]);
    expect(race.filter((result) => result.status === "fulfilled")).toHaveLength(1);
    await expect(finishLogin(db, "")).rejects.toThrow();
    const stale = await beginLogin(db, user.email, password);
    await db.loginChallenge.update({ where: { tokenHash: tokenHash(stale.token) }, data: { expiresAt: new Date(0) } });
    await expect(finishLogin(db, stale.token)).rejects.toThrow();
    const reset = await beginLogin(db, user.email, password);
    await db.user.update({ where: { id: user.id }, data: { sessionVersion: { increment: 1 } } });
    await expect(finishLogin(db, reset.token)).rejects.toThrow();
  });
  it("requires password, proof and acknowledgement, stores encrypted secrets and invalidates existing sessions", async () => {
    const user = await account();
    await expect(beginFactorSetup(db, user.id, "wrong")).rejects.toThrow();
    const before = await beginLogin(db, user.email, password);
    const setup = await beginFactorSetup(db, user.id, password);
    expect((await factorStatus(db, user.id)).enabled).toBe(false);
    await expect(confirmFactorSetup(db, user.id, "forged")).rejects.toThrow();
    const verified = await verifyFactorSetup(db, user.id, await code(setup.secret));
    expect(verified.codes).toHaveLength(10);
    await expect(verifyFactorSetup(db, user.id, await code(setup.secret))).rejects.toThrow();
    await confirmFactorSetup(db, user.id, verified.proof);
    expect(await factorStatus(db, user.id)).toMatchObject({ enabled: true, recoveryCodesRemaining: 10 });
    await expect(finishLogin(db, before.token)).rejects.toThrow();
    const factor = await personalAuth(db, user.id, async (_, __, row) => row);
    expect(factor.secret).not.toContain(setup.secret); expect(decryptFactor(factor.secret!, user.id)).toBe(setup.secret);
    expect(await resolveSessionIdentity(db, user.id, user.sessionVersion, true)).toBeNull();
    await expect(confirmFactorSetup(db, user.id, verified.proof)).rejects.toThrow();
  });
  it("consumes recovery codes exactly once even across independent, concurrent challenges", async () => {
    const user = await account(), factor = await enroll(user);
    const a = await beginLogin(db, user.email, password), b = await beginLogin(db, user.email, password);
    expect(a.requiresTwoFactor).toBe(true);
    const result = await Promise.allSettled([finishLogin(db, a.token, factor.codes[0], "recovery"), finishLogin(db, b.token, factor.codes[0], "recovery")]);
    expect(result.filter((r) => r.status === "fulfilled")).toHaveLength(1);
    expect((await factorStatus(db, user.id)).recoveryCodesRemaining).toBe(9);
    const c = await beginLogin(db, user.email, password);
    const currentCode = await code(factor.secret);
    // Setup's code must not also authorize a session during the same time step.
    await expect(finishLogin(db, c.token, currentCode)).rejects.toThrow();
    const row = await db.user.findUniqueOrThrow({ where: { id: user.id } });
    expect(await resolveSessionIdentity(db, user.id, row.sessionVersion, false)).toBeNull();
    expect(await resolveSessionIdentity(db, user.id, row.sessionVersion, true)).not.toBeNull();
  });
  it("persists failed attempts across challenges and enforces five tries per challenge and ten per account", async () => {
    const user = await account(); await enroll(user);
    for (let window = 0; window < 2; window++) {
      const login = await beginLogin(db, user.email, password);
      for (let i = 0; i < 5; i++) await expect(finishLogin(db, login.token, "invalid")).rejects.toThrow();
      await expect(finishLogin(db, login.token, "invalid")).rejects.toThrow(/verlopen/);
    }
    const login = await beginLogin(db, user.email, password);
    await expect(finishLogin(db, login.token, "invalid")).rejects.toThrow(/Te veel/);
    const factor = await personalAuth(db, user.id, async (_, __, row) => row);
    expect(factor.failures).toBe(10);
  });
  it("protects each member's factor from the workspace owner at the RLS layer", async () => {
    const owner = await account(), member = await account("VIEWER", owner.id);
    await enroll(member);
    await db.$transaction(async (tx) => {
      await setWorkspaceRlsContext(tx, owner.id, owner.id);
      expect(await tx.userTwoFactor.findUnique({ where: { userId: member.id } })).toBeNull();
      expect(await tx.twoFactorRecoveryCode.count({ where: { userId: member.id } })).toBe(0);
      expect((await tx.userTwoFactor.updateMany({ where: { userId: member.id }, data: { secret: "malicious" } })).count).toBe(0);
    });
  });
  it("retains the active factor during replacement and atomically invalidates old recovery codes", async () => {
    const user = await account(), original = await enroll(user);
    const setup = await beginFactorSetup(db, user.id, password, original.codes[0], "recovery");
    expect((await factorStatus(db, user.id)).enabled).toBe(true);
    const oldLogin = await beginLogin(db, user.email, password);
    await finishLogin(db, oldLogin.token, original.codes[1], "recovery");
    const replacement = await verifyFactorSetup(db, user.id, await code(setup.secret));
    await confirmFactorSetup(db, user.id, replacement.proof);
    const login = await beginLogin(db, user.email, password);
    await expect(finishLogin(db, login.token, original.codes[2], "recovery")).rejects.toThrow();
    await finishLogin(db, login.token, replacement.codes[0], "recovery");
    const regenerated = await manageFactor(db, user.id, password, replacement.codes[1]!, "recovery", "regenerate");
    expect(regenerated.codes).toHaveLength(10);
    await manageFactor(db, user.id, password, regenerated.codes[0]!, "recovery", "disable");
    expect(await factorStatus(db, user.id)).toMatchObject({ enabled: false, recoveryCodesRemaining: 0 });
  });
  it("keeps password-reset accounts protected and invalidates pending setup and challenges by version", async () => {
    const user = await account(), enrolled = await enroll(user);
    const login = await beginLogin(db, user.email, password);
    const replacement = await beginFactorSetup(db, user.id, password, enrolled.codes[0], "recovery");
    await db.user.update({ where: { id: user.id }, data: { passwordHash: upgradedPassword(password + "new"), sessionVersion: { increment: 1 } } });
    await expect(finishLogin(db, login.token, enrolled.codes[1], "recovery")).rejects.toThrow();
    await expect(verifyFactorSetup(db, user.id, await code(replacement.secret))).rejects.toThrow();
    expect((await beginLogin(db, user.email, password + "new")).requiresTwoFactor).toBe(true);
  });
  it("requires independent privileged recovery review and grants enrollment-only access", async () => {
    const user = await account(); await enroll(user);
    const before = await beginLogin(db, user.email, password);
    const operator = { operatorId: "verified-operator", ticket: "test-disposable", reason: "Test recovery identity verified" };
    await expect(issueRecoveryGrant(db, user.id, operator)).rejects.toThrow(/tweede/);
    const grant = await issueRecoveryGrant(db, user.id, { ...operator, secondReviewerId: "independent-reviewer" });
    await expect(finishLogin(db, before.token)).rejects.toThrow();
    await expect(beginLogin(db, user.email, password)).rejects.toThrow(/herstel/);
    const setup = await beginControlledRecovery(db, user.email, password, grant);
    await expect(beginControlledRecovery(db, user.email, password, grant)).rejects.toThrow();
    await expect(finishLogin(db, setup.token)).rejects.toThrow();
    await expect(verifyFactorSetup(db, user.id, await code(setup.secret))).rejects.toThrow();
    const checked = await verifyFactorSetup(db, user.id, await code(setup.secret), setup.token);
    await confirmFactorSetup(db, user.id, checked.proof, setup.token);
    const login = await beginLogin(db, user.email, password);
    await finishLogin(db, login.token, checked.codes[0], "recovery");
  });
  it("counts rate limits atomically across callers", async () => {
    const key = "2fa-test-rate:" + crypto.randomUUID(); bucketKeys.push(tokenHash(key));
    const outcomes = await Promise.allSettled(Array.from({ length: 5 }, () => authRateLimit(db, key, 3)));
    expect(outcomes.filter((r) => r.status === "fulfilled")).toHaveLength(3);
  });
});
