/** Explicit setting keys per settings UI page (avoids loading the full workspace settings table). */

export const EMAIL_SETTINGS_KEYS = [
  "email.from_name",
  "email.from_email",
  "email.from_title",
  "email.header_slogan",
  "email.signature",
  "email.daily_limit",
  "email.followup_days",
  "email.bcc",
  "email.reply_to",
  "email.footer",
  "email.master_shell_html",
  "email.custom_html",
] as const;

export const AI_SETTINGS_KEYS = [
  "api.ai_provider",
  "openclaw.model",
  "openclaw_language",
  "openclaw_tone",
  "openclaw_aggressiveness",
  "openclaw.max_tokens",
  "openclaw.auto_suggest",
  "openclaw.business_context",
] as const;

export const COMPANY_SETTINGS_KEYS = [
  "company.name",
  "company.website",
  "company.phone",
  "company.email",
  "company.address",
  "company.vat",
  "company.kbo",
  "company.iban",
  "company.niche",
  "company.footer_brand_name",
  "company.footer_tagline",
  "company.footer_description",
  "company.footer_email",
  "company.footer_phone",
  "company.footer_location",
  "company.footer_website_label",
  "company.footer_website_url",
  "company.footer_legal_line",
  "company.footer_copyright_line",
] as const;

export const SEO_SETTINGS_KEYS = [
  "seo.site_name",
  "seo.default_title",
  "seo.default_description",
  "seo.keywords",
  "seo.canonical_base_url",
  "seo.og_image_url",
  "seo.og_locale",
  "seo.twitter_card",
  "seo.twitter_site",
  "seo.robots_index",
  "seo.robots_follow",
  "seo.google_site_verification",
  "seo.bing_site_verification",
  "seo.yandex_verification",
  "seo.organization_name",
  "seo.organization_logo_url",
  "seo.structured_data_enabled",
  "seo.solution_pages_json",
  "seo.page_home_title",
  "seo.page_home_description",
  "seo.page_product_title",
  "seo.page_product_description",
  "seo.page_solutions_title",
  "seo.page_solutions_description",
  "seo.page_about_title",
  "seo.page_about_description",
  "seo.page_contact_title",
  "seo.page_contact_description",
] as const;

export const REVIEWS_SETTINGS_KEYS = [
  "reviews.embed_company",
  "reviews.embed_title",
  "reviews.embed_description",
  "reviews.embed_color",
  "reviews.google_url",
  "reviews.trustpilot_url",
  "reviews.facebook_url",
  "reviews.public_badge",
  "reviews.public_heading",
  "reviews.public_intro",
  "reviews.public_continue_positive_title",
  "reviews.public_continue_positive_body",
  "reviews.public_continue_negative_title",
  "reviews.public_continue_negative_body",
  "reviews.public_continue_button",
  "reviews.public_positive_title",
  "reviews.public_positive_body",
  "reviews.public_positive_cta",
  "reviews.public_positive_done",
  "reviews.public_feedback_title",
  "reviews.public_feedback_body",
  "reviews.public_feedback_placeholder",
  "reviews.public_feedback_submit",
  "reviews.public_feedback_success",
  "reviews.public_completed_message",
  "reviews.public_redirect_message",
  "reviews.embed_prompt",
  "reviews.embed_hint_initial",
  "reviews.embed_hint_positive",
  "reviews.embed_hint_negative",
  "reviews.embed_continue_positive_title",
  "reviews.embed_continue_positive_body",
  "reviews.embed_continue_negative_title",
  "reviews.embed_continue_negative_body",
  "reviews.embed_continue_button",
  "reviews.embed_positive_title",
  "reviews.embed_positive_body",
  "reviews.embed_platform_cta",
  "reviews.embed_platform_opened",
  "reviews.embed_missing_links",
  "reviews.embed_feedback_title",
  "reviews.embed_feedback_body",
  "reviews.embed_feedback_placeholder",
  "reviews.embed_feedback_submit",
  "reviews.embed_feedback_success",
] as const;

export const QUOTES_CONFIGURATOR_SETTINGS_KEYS = [
  "quotes.embed_badge",
  "quotes.embed_bg_color",
  "quotes.embed_category_icons_json",
  "quotes.embed_color",
  "quotes.embed_company_name",
  "quotes.embed_company_tagline",
  "quotes.embed_cta_label",
  "quotes.embed_dark_color",
  "quotes.embed_description",
  "quotes.embed_details_title",
  "quotes.embed_disclaimer",
  "quotes.embed_footer_contact",
  "quotes.embed_footer_phone",
  "quotes.embed_footer_website",
  "quotes.embed_icon_library_json",
  "quotes.embed_logo_url",
  "quotes.embed_mode",
  "quotes.embed_product_icons_json",
  "quotes.embed_product_specs_json",
  "quotes.embed_product_title",
  "quotes.embed_service_title",
  "quotes.embed_specs_title",
  "quotes.embed_step_details_hint",
  "quotes.embed_step_details_label",
  "quotes.embed_step_product_hint",
  "quotes.embed_step_product_label",
  "quotes.embed_step_service_hint",
  "quotes.embed_step_service_label",
  "quotes.embed_step_specs_hint",
  "quotes.embed_step_specs_label",
  "quotes.embed_title",
  "quotes.pdf_about_text",
  "quotes.pdf_about_title",
  "quotes.pdf_accent_color",
  "quotes.pdf_brand_name",
  "quotes.pdf_brand_tagline",
  "quotes.pdf_footer_text",
  "quotes.pdf_header_bg_color",
  "quotes.pdf_intro_text",
  "quotes.pdf_intro_title",
  "quotes.pdf_logo_url",
  "quotes.pdf_next_steps_json",
  "quotes.pdf_next_steps_title",
  "quotes.pdf_page_bg_color",
  "quotes.pdf_process_steps_json",
  "quotes.pdf_process_title",
  "quotes.pdf_services_cards_json",
  "quotes.pdf_services_title",
  "quotes.pdf_signature_client_title",
  "quotes.pdf_signature_company_role",
  "quotes.pdf_signature_company_signer",
  "quotes.pdf_signature_company_title",
  "quotes.pdf_tips_json",
  "quotes.pdf_tips_title",
] as const;

export const INTEGRATIONS_SETTINGS_KEYS = [
  "api.google_places_key",
  "integrations.google_oauth_client_id",
  "integrations.google_oauth_client_secret",
  "integrations.meta_app_id",
  "integrations.meta_app_secret",
  "social.autopost_enabled",
  "ads.autoads_enabled",
  "ads.default_currency",
  "ads.max_daily_budget_cents",
  "api.ai_provider",
  "api.anthropic_key",
  "api.openai_key",
  "api.deepseek_key",
  "email.smtp_host",
  "email.smtp_port",
  "email.smtp_user",
  "email.smtp_pass",
  "email.smtp_servername",
  "email.smtp_tls_reject_unauthorized",
  "email.imap_host",
  "email.imap_port",
  "email.imap_user",
  "email.imap_pass",
  "email.imap_tls",
  "company.email",
  "email.from_email",
  "bookings.google_oauth_account_email",
  "bookings.google_calendar_id",
  "bookings.google_sync_enabled",
  "bookings.google_service_account_email",
  "bookings.google_service_account_private_key",
] as const;

export const BOOKINGS_SETTINGS_KEYS = [
  "bookings.availability_end_time",
  "bookings.availability_start_time",
  "bookings.available_days",
  "bookings.default_approval_mode",
  "bookings.embed_color",
  "bookings.embed_duration",
  "bookings.embed_location_label",
  "bookings.embed_meeting_name",
  "bookings.embed_service_name",
  "bookings.embed_submit_text",
  "bookings.embed_theme",
  "bookings.embed_time_mode",
  "bookings.embed_title",
  "bookings.google_calendar_id",
  "bookings.google_calendar_timezone",
  "bookings.google_service_account_email",
  "bookings.google_service_account_private_key",
  "bookings.slot_minutes",
  "bookings.webhook_events",
  "bookings.webhook_secret",
  "bookings.webhook_url",
  "bookings.weekly_hours",
  "branding.company_name",
] as const;

export const ANALYTICS_SETTINGS_KEYS = [
  "analytics.enabled",
  "analytics.track_app_usage",
  "analytics.track_widget_views",
  "analytics.anonymize_ip",
  "analytics.respect_dnt",
  "analytics.ga4_measurement_id",
  "analytics.gtm_container_id",
  "analytics.plausible_domain",
  "analytics.meta_pixel_id",
  "analytics.linkedin_partner_id",
  "analytics.custom_head_script",
  "analytics.retention_days",
] as const;

export const CACHE_SETTINGS_KEYS = [
  "cache.dashboard_ttl_minutes",
  "cache.settings_ttl_seconds",
  "cache.client_stale_time_minutes",
  "cache.prefetch_enabled",
] as const;

export const CHATBOT_SETTINGS_KEYS = [
  "chatbot.auto_open_delay",
  "chatbot.avatar_url",
  "chatbot.company_name",
  "chatbot.knowledge_pages",
  "chatbot.language",
  "chatbot.position",
  "chatbot.primary_color",
  "chatbot.response_style",
  "chatbot.training_notes",
  "chatbot.welcome_message",
] as const;
