"use client";

import { useState } from "react";
import { trpc } from "@/lib/trpc/client";
import { QueryErrorState } from "@/components/feedback/query-error-state";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, Label, Skeleton, Textarea } from "@digitify/ui";
import { Loader2, Pause, Play, Plus, SearchCheck, Trash2, TrendingDown, TrendingUp } from "lucide-react";

const numberLabel = (value: number | null) => value === null ? "Nog niet gemeten" : `#${value}`;

export default function SeoPage() {
  const utils = trpc.useUtils();
  const overview = trpc.seo.overview.useQuery(undefined, { staleTime: 10_000 });
  const [keyword, setKeyword] = useState("");
  const [domainId, setDomainId] = useState("");
  const [currentRank, setCurrentRank] = useState("");
  const [competitorName, setCompetitorName] = useState("");
  const [competitorUrl, setCompetitorUrl] = useState("");
  const [competitorNotes, setCompetitorNotes] = useState("");
  const createKeyword = trpc.seo.createKeyword.useMutation({ onSuccess: () => { setKeyword(""); setCurrentRank(""); void utils.seo.overview.invalidate(); } });
  const setStatus = trpc.seo.setKeywordStatus.useMutation({ onSuccess: () => void utils.seo.overview.invalidate() });
  const deleteKeyword = trpc.seo.deleteKeyword.useMutation({ onSuccess: () => void utils.seo.overview.invalidate() });
  const createCompetitor = trpc.seo.createCompetitor.useMutation({ onSuccess: () => { setCompetitorName(""); setCompetitorUrl(""); setCompetitorNotes(""); void utils.seo.overview.invalidate(); } });
  const deleteCompetitor = trpc.seo.deleteCompetitor.useMutation({ onSuccess: () => void utils.seo.overview.invalidate() });

  if (overview.isLoading) return <div className="app-page space-y-5"><Skeleton className="h-24 rounded-xl" /><div className="grid gap-3 md:grid-cols-5">{[1, 2, 3, 4, 5].map((item) => <Skeleton key={item} className="h-24 rounded-xl" />)}</div><Skeleton className="h-72 rounded-xl" /></div>;
  if (overview.error) return <div className="app-page"><QueryErrorState message={overview.error.message} onRetry={() => overview.refetch()} /></div>;
  const data = overview.data;
  if (!data) return null;

  return <div className="app-page space-y-5">
    <div className="app-page-header flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div className="app-page-heading"><div className="mb-2 flex items-center gap-2 text-primary"><SearchCheck className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-wide">Analyse</span></div><h1 className="app-page-title">SEO</h1><p className="app-page-subtitle">Volg zoekwoorden, technische gezondheid en concurrenten vanuit één werkplek.</p></div><Badge variant="outline">Lokale tracking · geen externe provider verbonden</Badge></div>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[
      ["Zoekwoorden", data.stats.trackedKeywords], ["Gemiddelde positie", data.stats.averageRank ? `#${data.stats.averageRank}` : "—"], ["Verbeterd", data.stats.improved], ["Gedaald", data.stats.declined], ["Geaudite domeinen", `${data.stats.auditedDomains}/${data.stats.domains}`],
    ].map(([label, value]) => <Card key={label} className="app-surface"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p></CardContent></Card>)}</div>

    <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <Card className="app-surface"><CardHeader className="pb-3"><CardTitle className="text-base">Zoekwoorden volgen</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_120px_auto] sm:items-end"><div className="space-y-2"><Label htmlFor="seo-keyword">Zoekwoord</Label><Input id="seo-keyword" value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="webdesign gent" /></div><div className="space-y-2"><Label htmlFor="seo-domain">Domein</Label><select id="seo-domain" value={domainId} onChange={(event) => setDomainId(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Alle domeinen</option>{data.audits.map((domain) => <option key={domain.id} value={domain.id}>{domain.domainName}</option>)}</select></div><div className="space-y-2"><Label htmlFor="seo-rank">Positie</Label><Input id="seo-rank" type="number" min="1" max="1000" value={currentRank} onChange={(event) => setCurrentRank(event.target.value)} placeholder="—" /></div><Button disabled={!keyword.trim() || createKeyword.isPending} onClick={() => createKeyword.mutate({ keyword, domainId: domainId || undefined, currentRank: currentRank ? Number(currentRank) : undefined })}>{createKeyword.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Toevoegen</Button></div>{createKeyword.error ? <p className="text-sm text-destructive">{createKeyword.error.message}</p> : null}
        {data.keywords.length === 0 ? <EmptyState icon={<SearchCheck />} title="Nog geen zoekwoorden" description="Voeg een zoekwoord toe om posities handmatig te volgen." /> : <div className="divide-y rounded-lg border">{data.keywords.map((item) => { const delta = item.currentRank !== null && item.previousRank !== null ? item.previousRank - item.currentRank : null; return <div key={item.id} className="flex flex-col gap-2 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-medium">{item.keyword}</p><p className="truncate text-xs text-muted-foreground">{item.domainName} · {item.status === "TRACKING" ? "Actief" : "Gepauzeerd"}</p></div><div className="flex items-center gap-2"><span className="text-sm font-semibold">{numberLabel(item.currentRank)}</span>{delta !== null ? <span className={`flex items-center text-xs ${delta > 0 ? "text-emerald-600" : delta < 0 ? "text-destructive" : "text-muted-foreground"}`}>{delta > 0 ? <TrendingUp className="mr-1 h-3.5 w-3.5" /> : delta < 0 ? <TrendingDown className="mr-1 h-3.5 w-3.5" /> : null}{delta > 0 ? `+${delta}` : delta}</span> : null}<Button size="icon" variant="ghost" title={item.status === "TRACKING" ? "Pauzeren" : "Hervatten"} onClick={() => setStatus.mutate({ id: item.id, status: item.status === "TRACKING" ? "PAUSED" : "TRACKING" })}>{item.status === "TRACKING" ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</Button><Button size="icon" variant="ghost" title="Verwijderen" onClick={() => deleteKeyword.mutate({ id: item.id })}><Trash2 className="h-4 w-4" /></Button></div></div>; })}</div>}
      </CardContent></Card>

      <Card className="app-surface"><CardHeader className="pb-3"><CardTitle className="text-base">Concurrent volgen</CardTitle></CardHeader><CardContent className="space-y-3"><div className="space-y-2"><Label htmlFor="competitor-name">Naam</Label><Input id="competitor-name" value={competitorName} onChange={(event) => setCompetitorName(event.target.value)} placeholder="Concurrent BV" /></div><div className="space-y-2"><Label htmlFor="competitor-url">Website</Label><Input id="competitor-url" value={competitorUrl} onChange={(event) => setCompetitorUrl(event.target.value)} placeholder="https://voorbeeld.be" /></div><div className="space-y-2"><Label htmlFor="competitor-notes">Notities</Label><Textarea id="competitor-notes" rows={2} value={competitorNotes} onChange={(event) => setCompetitorNotes(event.target.value)} placeholder="Wat wil je vergelijken?" /></div><Button disabled={!competitorName.trim() || !competitorUrl.trim() || createCompetitor.isPending} onClick={() => createCompetitor.mutate({ name: competitorName, url: competitorUrl, notes: competitorNotes || undefined })}>{createCompetitor.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Concurrent toevoegen</Button>{createCompetitor.error ? <p className="text-sm text-destructive">{createCompetitor.error.message}</p> : null}<div className="divide-y rounded-lg border">{data.competitors.length === 0 ? <p className="p-3 text-sm text-muted-foreground">Nog geen concurrenten toegevoegd.</p> : data.competitors.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-3"><div className="min-w-0"><p className="truncate font-medium">{item.name}</p><a className="block truncate text-xs text-primary hover:underline" href={item.url} target="_blank" rel="noreferrer">{item.url}</a></div><Button size="icon" variant="ghost" title="Verwijderen" onClick={() => deleteCompetitor.mutate({ id: item.id })}><Trash2 className="h-4 w-4" /></Button></div>)}</div></CardContent></Card>
    </div>

    <Card className="app-surface"><CardHeader className="pb-3"><CardTitle className="text-base">Technische SEO-overzicht</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.audits.length === 0 ? <div className="md:col-span-2 xl:col-span-3"><EmptyState icon={<SearchCheck />} title="Nog geen domeinen" description="Voeg eerst een domein toe om technische SEO-audits te bekijken." /></div> : data.audits.map((domain) => <div key={domain.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{domain.domainName}</p><p className="text-xs text-muted-foreground">{domain.lastAnalyzedAt ? `Laatste audit ${new Date(domain.lastAnalyzedAt).toLocaleDateString("nl-BE")}` : "Nog niet geanalyseerd"}</p></div><Badge variant={domain.score !== null && domain.score >= 70 ? "default" : "outline"}>{domain.score !== null ? `${domain.score}/100` : "—"}</Badge></div><Button variant="ghost" size="sm" className="mt-2 px-0" asChild><a href={`/domains/${domain.id}`}>Domeindetails bekijken</a></Button></div>)}</div></CardContent></Card>
  </div>;
}
