"use client";

import { useState } from "react";
import { trpc } from "@/lib/trpc/client";
import { QueryErrorState } from "@/components/feedback/query-error-state";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Skeleton } from "@digitify/ui";
import { CheckCircle2, GitBranch, Loader2, Play, Plus, ShieldCheck, TestTube2 } from "lucide-react";

const triggerLabels = { LEAD_CREATED: "Nieuwe lead", LEAD_STATUS_CHANGED: "Leadstatus gewijzigd", FORM_SUBMITTED: "Formulier ingestuurd", TASK_DUE: "Taak verloopt" } as const;
const statusLabels = { DRAFT: "Concept", ACTIVE: "Actief", PAUSED: "Gepauzeerd", ARCHIVED: "Gearchiveerd" } as const;

export default function AutomationsPage() {
  const [name, setName] = useState("");
  const [taskTitle, setTaskTitle] = useState("");
  const [trigger, setTrigger] = useState<keyof typeof triggerLabels>("LEAD_CREATED");
  const utils = trpc.useUtils();
  const workflows = trpc.workflow.list.useQuery();
  const create = trpc.workflow.create.useMutation({ onSuccess: () => { setName(""); setTaskTitle(""); void utils.workflow.list.invalidate(); } });
  const setStatus = trpc.workflow.setStatus.useMutation({ onSuccess: () => void utils.workflow.list.invalidate() });
  const dryRun = trpc.workflow.dryRun.useMutation();
  const run = trpc.workflow.run.useMutation({ onSuccess: () => void utils.workflow.list.invalidate() });

  return (
    <div className="app-page space-y-5">
      <div className="app-page-header flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div className="app-page-heading"><div className="mb-2 flex items-center gap-2 text-primary"><GitBranch className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-wide">Automatisering</span></div><h1 className="app-page-title">Workflows</h1><p className="app-page-subtitle">Laat terugkerend werk als taak klaarzetten, met controle en herhaalbare runs.</p></div><Badge variant="outline"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />E-mail blijft goedkeuringsplichtig</Badge></div>
      <Card className="app-surface"><CardHeader className="pb-3"><CardTitle className="text-base">Veilige workflow aanmaken</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3 md:items-end"><div className="space-y-2"><Label htmlFor="workflow-name">Naam</Label><Input id="workflow-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nieuwe lead opvolgen" /></div><div className="space-y-2"><Label htmlFor="workflow-trigger">Trigger</Label><Select value={trigger} onValueChange={(value) => setTrigger(value as keyof typeof triggerLabels)}><SelectTrigger id="workflow-trigger"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(triggerLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="workflow-task">Automatische taak</Label><Input id="workflow-task" value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Bel de nieuwe lead" /></div><Button disabled={!name.trim() || !taskTitle.trim() || create.isPending} onClick={() => create.mutate({ name: name.trim(), trigger, actions: [{ type: "CREATE_TASK", title: taskTitle.trim() }] })}>{create.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}Aanmaken</Button></CardContent>{create.error ? <p className="px-6 pb-4 text-sm text-destructive">{create.error.message}</p> : null}</Card>
      {workflows.isLoading ? <div className="grid gap-3 md:grid-cols-2">{[1, 2].map((item) => <Skeleton key={item} className="h-48 rounded-xl" />)}</div> : workflows.error ? <QueryErrorState message={workflows.error.message} onRetry={() => workflows.refetch()} /> : (workflows.data ?? []).length === 0 ? <Card className="app-surface"><CardContent className="p-0"><EmptyState icon={<GitBranch />} title="Nog geen workflows" description="Maak een workflow om automatisch opvolgtaken klaar te zetten." /></CardContent></Card> : <div className="grid gap-3 md:grid-cols-2">{workflows.data?.map((workflow) => { const key = `${workflow.id}-${Date.now()}`; const actions = Array.isArray(workflow.actions) ? workflow.actions as Array<{ type?: string; title?: string }> : []; return <Card key={workflow.id} className="app-surface"><CardHeader className="flex flex-row items-start justify-between space-y-0 pb-3"><div><CardTitle className="text-base">{workflow.name}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{triggerLabels[workflow.trigger as keyof typeof triggerLabels] ?? workflow.trigger}</p></div><Badge variant={workflow.status === "ACTIVE" ? "default" : "outline"}>{statusLabels[workflow.status]}</Badge></CardHeader><CardContent className="space-y-3"><div className="rounded-lg border p-3 text-sm"><p className="text-xs uppercase tracking-wide text-muted-foreground">Acties</p>{actions.map((action, index) => <p key={`${action.title}-${index}`} className="mt-1 flex items-center gap-2"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />{action.title}</p>)}</div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => setStatus.mutate({ id: workflow.id, status: workflow.status === "ACTIVE" ? "PAUSED" : "ACTIVE" })}>{workflow.status === "ACTIVE" ? "Pauzeren" : "Activeren"}</Button><Button size="sm" variant="outline" disabled={dryRun.isPending} onClick={() => dryRun.mutate({ workflowId: workflow.id, idempotencyKey: `dry-${key}` })}><TestTube2 className="mr-1.5 h-3.5 w-3.5" />Dry-run</Button>{workflow.status === "ACTIVE" ? <Button size="sm" variant="outline" disabled={run.isPending} onClick={() => run.mutate({ workflowId: workflow.id, idempotencyKey: `run-${key}` })}><Play className="mr-1.5 h-3.5 w-3.5" />Uitvoeren</Button> : null}</div>{dryRun.data?.workflowId === workflow.id ? <p className="text-xs text-emerald-700">Dry-run opgeslagen; e-mailacties zouden door goedkeuring worden geblokkeerd.</p> : null}{dryRun.error ? <p className="text-xs text-destructive">{dryRun.error.message}</p> : null}{run.error ? <p className="text-xs text-destructive">{run.error.message}</p> : null}</CardContent></Card>; })}</div>}
    </div>
  );
}
